on: pull_request
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install linux packages
        run: sudo apt-get update && sudo apt-get install wine devscripts sbuild
      - name: Download node.js
        run: curl -o /tmp/node.tar.xz https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz && sudo tar --strip-components=1 -xJvf /tmp/node.tar.xz -C /usr/local
      - name: Install deps
        run: npm install
      - name: Create apps folder
        run: mkdir -p apps
      - name: List files
        run: ls -lR .
      - name: build linux64 release
        run: node ./node_modules/gulp/bin/gulp.js release --platform=linux64 -LLLL
      - name: List files 2
        run: ls -lR .
      - name: build win64 release
        run: node ./node_modules/gulp/bin/gulp.js release --platform=win64
      - name: List files 3
        run: ls -lR .
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: apps/*.{zip,rpm,deb,pkg,dmg,tar.gz}
